//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vendas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int Codprod { get; set; }
        public string Prodnome { get; set; }
        public Nullable<double> Custo { get; set; }
        public Nullable<double> Preco_final { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<double> Lucro { get; set; }
        public Nullable<double> Lucro_percentual { get; set; }

        public Produto()
        { 

        }

        public Produto(int codprod, string prodnome, double custo, double preco_final, int quantidade, double lucro, double lucro_percentual )
        {
            Codprod          = codprod;
            Prodnome         = prodnome;
            Custo            = custo;
            Preco_final      = preco_final;
            Quantidade       = quantidade;
            Lucro            = lucro;
            Lucro_percentual = lucro_percentual;
        }
    }
}
