//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vendas.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public Nullable<System.DateTime> DtNascimento { get; set; }
        public Nullable<System.DateTime> DtCadastro { get; set; }
        public string Tipo { get; set; }
        public string senha { get; set; }
        public string usuario { get; set; }
        public string celular { get; set; }
    }
}
