//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vendas.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int Codprod { get; set; }
        public string Prodnome { get; set; }
        public Nullable<double> Custo { get; set; }
        public Nullable<double> Preco_final { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<double> Lucro { get; set; }
        public Nullable<double> Lucro_percentual { get; set; }
    }
}
